// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/order.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlashSaleService_RushBuy_FullMethodName = "/api.FlashSaleService/RushBuy"
)

// FlashSaleServiceClient is the client API for FlashSaleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlashSaleServiceClient interface {
	RushBuy(ctx context.Context, in *RushBuyRequest, opts ...grpc.CallOption) (*RushBuyResponse, error)
}

type flashSaleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlashSaleServiceClient(cc grpc.ClientConnInterface) FlashSaleServiceClient {
	return &flashSaleServiceClient{cc}
}

func (c *flashSaleServiceClient) RushBuy(ctx context.Context, in *RushBuyRequest, opts ...grpc.CallOption) (*RushBuyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RushBuyResponse)
	err := c.cc.Invoke(ctx, FlashSaleService_RushBuy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlashSaleServiceServer is the server API for FlashSaleService service.
// All implementations must embed UnimplementedFlashSaleServiceServer
// for forward compatibility.
type FlashSaleServiceServer interface {
	RushBuy(context.Context, *RushBuyRequest) (*RushBuyResponse, error)
	mustEmbedUnimplementedFlashSaleServiceServer()
}

// UnimplementedFlashSaleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlashSaleServiceServer struct{}

func (UnimplementedFlashSaleServiceServer) RushBuy(context.Context, *RushBuyRequest) (*RushBuyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RushBuy not implemented")
}
func (UnimplementedFlashSaleServiceServer) mustEmbedUnimplementedFlashSaleServiceServer() {}
func (UnimplementedFlashSaleServiceServer) testEmbeddedByValue()                          {}

// UnsafeFlashSaleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlashSaleServiceServer will
// result in compilation errors.
type UnsafeFlashSaleServiceServer interface {
	mustEmbedUnimplementedFlashSaleServiceServer()
}

func RegisterFlashSaleServiceServer(s grpc.ServiceRegistrar, srv FlashSaleServiceServer) {
	// If the following call panics, it indicates UnimplementedFlashSaleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlashSaleService_ServiceDesc, srv)
}

func _FlashSaleService_RushBuy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RushBuyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlashSaleServiceServer).RushBuy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlashSaleService_RushBuy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlashSaleServiceServer).RushBuy(ctx, req.(*RushBuyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlashSaleService_ServiceDesc is the grpc.ServiceDesc for FlashSaleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlashSaleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.FlashSaleService",
	HandlerType: (*FlashSaleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RushBuy",
			Handler:    _FlashSaleService_RushBuy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/order.proto",
}
