// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/order.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RushBuyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RushBuyRequest) Reset() {
	*x = RushBuyRequest{}
	mi := &file_api_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RushBuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RushBuyRequest) ProtoMessage() {}

func (x *RushBuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RushBuyRequest.ProtoReflect.Descriptor instead.
func (*RushBuyRequest) Descriptor() ([]byte, []int) {
	return file_api_order_proto_rawDescGZIP(), []int{0}
}

func (x *RushBuyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RushBuyRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type RushBuyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	OrderSn       string                 `protobuf:"bytes,3,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RushBuyResponse) Reset() {
	*x = RushBuyResponse{}
	mi := &file_api_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RushBuyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RushBuyResponse) ProtoMessage() {}

func (x *RushBuyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RushBuyResponse.ProtoReflect.Descriptor instead.
func (*RushBuyResponse) Descriptor() ([]byte, []int) {
	return file_api_order_proto_rawDescGZIP(), []int{1}
}

func (x *RushBuyResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RushBuyResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RushBuyResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

var File_api_order_proto protoreflect.FileDescriptor

const file_api_order_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/order.proto\x12\x03api\"H\n" +
	"\x0eRushBuyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\"V\n" +
	"\x0fRushBuyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\border_sn\x18\x03 \x01(\tR\aorderSn2H\n" +
	"\x10FlashSaleService\x124\n" +
	"\aRushBuy\x12\x13.api.RushBuyRequest\x1a\x14.api.RushBuyResponseB\aZ\x05./apib\x06proto3"

var (
	file_api_order_proto_rawDescOnce sync.Once
	file_api_order_proto_rawDescData []byte
)

func file_api_order_proto_rawDescGZIP() []byte {
	file_api_order_proto_rawDescOnce.Do(func() {
		file_api_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_order_proto_rawDesc), len(file_api_order_proto_rawDesc)))
	})
	return file_api_order_proto_rawDescData
}

var file_api_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_order_proto_goTypes = []any{
	(*RushBuyRequest)(nil),  // 0: api.RushBuyRequest
	(*RushBuyResponse)(nil), // 1: api.RushBuyResponse
}
var file_api_order_proto_depIdxs = []int32{
	0, // 0: api.FlashSaleService.RushBuy:input_type -> api.RushBuyRequest
	1, // 1: api.FlashSaleService.RushBuy:output_type -> api.RushBuyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_order_proto_init() }
func file_api_order_proto_init() {
	if File_api_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_order_proto_rawDesc), len(file_api_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_order_proto_goTypes,
		DependencyIndexes: file_api_order_proto_depIdxs,
		MessageInfos:      file_api_order_proto_msgTypes,
	}.Build()
	File_api_order_proto = out.File
	file_api_order_proto_goTypes = nil
	file_api_order_proto_depIdxs = nil
}
